### ISSUE TITLE
Breid de arduino code uit tot 3 k.a.k.u.

### ISSUE THREAD

**Issue by SvenMark** [Informotics/Domotics#1]
**Breid de gegeven voorbeeldcode (Arduino en Xamarin, zoals beschikbaar
gesteld via BB) uit tot een domotica-systeem dat:**
Minstens 3 RF-stopcontacten afzonderlijk kan aansturen. Van elk
stopcontact is op de Arduino én op de app de actuele status te zien
(aan/uit). Het interface is functioneel, logisch, responsief en
gebruiksvriendelijk. Meer info bij het college “User Experience”.

**Comment by RendallSchijven** [comment]
Finished
